[package]
name = "engine-testing"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = true
codegen-units = 1
strip = true

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.29", features = [
    "derive",
    "cargo",
    "env",
    "unicode",
    "wrap_help",
] }
oxc = { version = "0.51.0", features = ["serialize"] }
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter", "tracing-log"] }
